import { Subscription } from "./types"

export const mockSubscriptions: Subscription[] = [
  {
    id: "1",
    name: "Netflix",
    logo: "/logos/netflix_logo.png",
    amount: 15.99,
    frequency: "monthly",
    confidence: "high",
    confidenceReason: "Consistent monthly charges for 12+ months with identical amounts",
    flags: [],
    lastCharges: [
      { date: "2026-01-15", amount: 15.99, description: "NETFLIX.COM" },
      { date: "2025-12-15", amount: 15.99, description: "NETFLIX.COM" },
      { date: "2025-11-15", amount: 15.99, description: "NETFLIX.COM" },
      { date: "2025-10-15", amount: 15.99, description: "NETFLIX.COM" },
    ],
    category: "Entertainment",
    status: "active",
    statementPeriod: "Jan 2025 - Jan 2026",
    sourceRef: "Chase Visa ****4521",
  },
  {
    id: "2",
    name: "Spotify",
    logo: "/logos/spotify_logo.png",
    amount: 10.99,
    frequency: "monthly",
    confidence: "high",
    confidenceReason: "Regular monthly pattern detected across 8 months",
    flags: ["price increase"],
    lastCharges: [
      { date: "2026-01-10", amount: 10.99, description: "SPOTIFY USA" },
      { date: "2025-12-10", amount: 10.99, description: "SPOTIFY USA" },
      { date: "2025-11-10", amount: 9.99, description: "SPOTIFY USA" },
      { date: "2025-10-10", amount: 9.99, description: "SPOTIFY USA" },
    ],
    category: "Entertainment",
    status: "active",
    statementPeriod: "Jun 2025 - Jan 2026",
    sourceRef: "Chase Visa ****4521",
  },
  {
    id: "3",
    name: "Adobe Creative Cloud",
    logo: "/logos/adobe_logo.png",
    amount: 54.99,
    frequency: "monthly",
    confidence: "high",
    confidenceReason: "Consistent billing pattern with Adobe merchant ID",
    flags: ["review"],
    lastCharges: [
      { date: "2026-01-05", amount: 54.99, description: "ADOBE *CREATIVE CLD" },
      { date: "2025-12-05", amount: 54.99, description: "ADOBE *CREATIVE CLD" },
      { date: "2025-11-05", amount: 54.99, description: "ADOBE *CREATIVE CLD" },
    ],
    category: "Software",
    status: "active",
    statementPeriod: "Nov 2025 - Jan 2026",
    sourceRef: "Amex ****1234",
  },
  {
    id: "4",
    name: "Gym Membership",
    logo: "/logos/af_logo.png",
    amount: 49.00,
    frequency: "monthly",
    confidence: "medium",
    confidenceReason: "Monthly pattern detected but merchant name varies slightly",
    flags: ["possible duplicate"],
    lastCharges: [
      { date: "2026-01-02", amount: 49.00, description: "PLANET FITNESS" },
      { date: "2025-12-02", amount: 49.00, description: "PLNT FITNESS" },
      { date: "2025-11-02", amount: 49.00, description: "PLANET FITNESS" },
    ],
    category: "Health & Fitness",
    status: "active",
    statementPeriod: "Nov 2025 - Jan 2026",
    sourceRef: "Chase Visa ****4521",
  },
  {
    id: "5",
    name: "Cloud Storage",
    logo: "/logos/cloud.png",
    amount: 2.99,
    frequency: "monthly",
    confidence: "low",
    confidenceReason: "Only 2 charges detected, insufficient history",
    flags: ["low confidence"],
    lastCharges: [
      { date: "2026-01-01", amount: 2.99, description: "GOOGLE *STORAGE" },
      { date: "2025-12-01", amount: 2.99, description: "GOOGLE *STORAGE" },
    ],
    category: "Software",
    status: "active",
    statementPeriod: "Dec 2025 - Jan 2026",
    sourceRef: "Chase Visa ****4521",
  },
  {
    id: "6",
    name: "Domain Renewal",
    logo: "/logos/domain.png",
    amount: 14.99,
    frequency: "yearly",
    confidence: "medium",
    confidenceReason: "Annual charge detected, matches domain registrar pattern",
    flags: ["multiple charges"],
    lastCharges: [
      { date: "2026-01-08", amount: 14.99, description: "NAMECHEAP INC" },
      { date: "2026-01-08", amount: 12.99, description: "NAMECHEAP INC" },
      { date: "2025-01-08", amount: 14.99, description: "NAMECHEAP INC" },
    ],
    category: "Software",
    status: "active",
    statementPeriod: "Jan 2025 - Jan 2026",
    sourceRef: "Amex ****1234",
  },
  {
    id: "7",
    name: "News Subscription",
    logo: "/logos/news.png",
    amount: 4.99,
    frequency: "weekly",
    confidence: "medium",
    confidenceReason: "Weekly pattern detected but amount varies occasionally",
    flags: ["review"],
    lastCharges: [
      { date: "2026-01-14", amount: 4.99, description: "NYT DIGITAL" },
      { date: "2026-01-07", amount: 4.99, description: "NYT DIGITAL" },
      { date: "2025-12-31", amount: 4.99, description: "NYT DIGITAL" },
      { date: "2025-12-24", amount: 0.99, description: "NYT DIGITAL PROMO" },
    ],
    category: "News & Media",
    status: "active",
    statementPeriod: "Dec 2025 - Jan 2026",
    sourceRef: "Chase Visa ****4521",
  },
]
